### ISSUE TITLE
File size reduction: No composites?

### ISSUE THREAD

**Issue by madig** [googlefonts/googlesans#113]
The sources currently have a lot of precomposed glyphs like `adieresis`. I wonder if it made sense to instead provide only the base outline glyphs and marks (plus precomposed complicated glyphs) but otherwise leave composition up to HarfBuzz? I think this won't work for Adobe software, but might be a way to reduce the file size for HarfBuzz platforms?

**Comment by m4rc1e** [comment]
We had this idea for Roboto VF, https://github.com/TypeNetwork/Roboto/issues/46. If I remember correctly, it only worked in Chrome and Edge so we gave up.

**Comment by madig** [comment]
Dayum. Might still be an option for Android/app distribution?

**Comment by chrissimpkins** [comment]
I need to work on size projections and speak with the Pixel team about file size considerations as we merge the i18n work.  Let's not reduce breadth of application / environment support in the name of file size reduction for the moment, even for a new build target.  I'm trying to avoid lots of different build targets that will require maintenance and multiple distribution approaches unless/until we know that we need them.  There may well be a case to be made for a max file size optimized build target that excludes some use cases.  I'll tag issues with these file size reduction ideas so that we can circle back to these issues when I know more.

For future reference, here is Adam's investigation of support with the ttfdiet tool https://github.com/twardoch/ttfdiet#test-results.
