### ISSUE TITLE
Greek features: duplicate etatonos -> Etatonos feature?

### ISSUE THREAD

**Issue by madig** [googlefonts/googlesans#157]
The  following feature is present in both `locl` and `case`, is this intentional? In what context is it used?

> `sub [space hyphen softhyphen endash emdash underscore] etatonos' [space hyphen softhyphen endash emdash underscore comma] by Etatonos;`

@irenevl

**Comment by irenevlachou** [comment]
locl, I don't know how this showed up in case

**Comment by madig** [comment]
Ok, I'll remove it. How is it typically used, can you give me a short snippet of text (i.e. a word) and what glyphs you expect the shaper to output?

**Comment by irenevlachou** [comment]
Capitalising Greek results to dropping all the accents. The only exception is the disjunctive Eta, which translates to English “or” which in order to be separated from the feminine article has always a tonos. So it's important for language context to keep it even in all caps setting.

Example:

All lower case:

`Μήλα ή αχλάδια;`

All upper case:

`ΜΗΛΑ Ή ΑΧΛΑΔΙΑ;`

**Comment by chrissimpkins** [comment]
@irenevl I want to confirm that we understand https://github.com/googlefonts/googlesans/issues/157#issuecomment-774117550 correctly.

When I enter the string `Μήλα ή αχλάδια` I see `Ή` by default, not `ή`.  

![etatonos2](https://user-images.githubusercontent.com/4249591/107160723-ff411200-6965-11eb-879f-688a2209c704.gif)

When I enter `ΜΗΛΑ Ή ΑΧΛΑΔΙΑ`, I see the string without a substitution.

This is correct?

**Comment by irenevlachou** [comment]
I think I was wrong, in order to work as it supposed to, it needed to be in the case since it's about case conversion. The locl doesn't affect it. much since it's irrelevant to language specification.
Should I change it back to all UFOs?

**Comment by madig** [comment]
What do you mean all UFOs?

**Comment by irenevlachou** [comment]
I meant the feature file but I haven't seen a separate external one.

**Comment by madig** [comment]
I'm working on that. We just needed a text string, the accompanying feature and the expected result :)

**Comment by irenevlachou** [comment]
Great! the string that I shared above will be enough I think.

In normal lower case:

μήλα ή αχλάδια;

but In all caps transformation, eta keeps the tonos when the rest drop it:
All upper case:

ΜΗΛΑ Ή ΑΧΛΑΔΙΑ;

**Comment by chrissimpkins** [comment]
@madig it sounds like this will land is the case feature.  Do you want me to update #166 with the following strings?

`Μήλα ή αχλάδια`
`ΜΗΛΑ Ή ΑΧΛΑΔΙΑ`

or wait until the PR with these fea changes?

**Comment by madig** [comment]
Go ahead, I'll need those strings precisely for updating the feas :grimacing:

**Comment by moyogo** [comment]
Isn't this meant to be for the all-capital sequences that should drop all tonos except on the word ή and that should add dieresis on iota or upsilon in diphthongs?

**Comment by chrissimpkins** [comment]
> @madig it sounds like this will land is the case feature. Do you want me to update #166 with the following strings?
> 
> `Μήλα ή αχλάδια`
> `ΜΗΛΑ Ή ΑΧΛΑΔΙΑ`
> 
> or wait until the PR with these fea changes?

These strings were added to our regression tests for the case feature in https://github.com/googlefonts/googlesans/pull/166/commits/c0974ad7568480206c8d84c7403b10aa8572f6da

**Comment by chrissimpkins** [comment]
> > @madig it sounds like this will land is the case feature. Do you want me to update #166 with the following strings?
> > `Μήλα ή αχλάδια`
> > `ΜΗΛΑ Ή ΑΧΛΑΔΙΑ`
> > or wait until the PR with these fea changes?
> 
> These strings were added to our regression tests for the case feature in [c0974ad](https://github.com/googlefonts/googlesans/commit/c0974ad7568480206c8d84c7403b10aa8572f6da)

This is what we see in GS v3.003 production files:

`Μήλα ή αχλάδια`:

```
Mu|etatonos|lambda|alpha|space|Etatonos|space|alpha|chi|lambda|alphatonos|delta|iota|alpha
```

`ΜΗΛΑ Ή ΑΧΛΑΔΙΑ`:

```
Mu|Eta|Lambda|Alpha|space|Etatonos|space|Alpha|Chi|Lambda|Alpha|uni0394|Iota|Alpha
```

**Comment by moyogo** [comment]
@chrissimpkins this doesn't test anything meaningful.
The `sub [space hyphen softhyphen endash emdash underscore] etatonos' [space hyphen softhyphen endash emdash underscore comma] by Etatonos;` isn't correct either. The locl feature should definitely not uppercase the etatonos when between spaces because the ή word shouldn't always be uppercase, nor should the case feature because the case feature is for adjusting glyphs in all-caps sequences and not for uppercasing glyphs.

There should be a feature that drops the tonos marks in all-capital sequences, except on the word ή, and adds dieresis on the iota or upsilon in diphthongs.

The tonos-dropping is described on Gerry Leonidas’ [*Case conversion for monotonic Greek*](https://leonidas.net/greek-type-design/case-conversion-for-monotonic-greek/) and both tonos-dropping and dieresis-adding are described on MDN’s [*CSS text-transform* documentation page](https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform#uppercase_greek_vowels).

Specifically, this means that `"Μήλα ή αχλάδια".upper()"`, in other words `"ΜΉΛΑ Ή ΑΧΛΆΔΙΑ"` looks like `"ΜΗΛΑ Ή ΑΧΛΑΔΙΑ"`. We should have:

`ΜΉΛΑ Ή ΑΧΛΆΔΙΑ`:
```
 Mu|Eta|Lambda|Alpha|space|Etatonos|space|Alpha|Chi|Lambda|Alpha|uni0394|Iota|Alpha
```
instead of the current
`ΜΉΛΑ Ή ΑΧΛΆΔΙΑ`:
```
Mu|Etatonos|Lambda|Alpha|space|Etatonos|space|Alpha|Chi|Lambda|Alphatonos|uni0394|Iota|Alpha
```

**Comment by madig** [comment]
> There should be a feature 

And which one? 😬

**Comment by moyogo** [comment]
Roughly the behaviour can be implemented like this, in the `calt` feature for example, and without the case and locl substitution. It does the following:
1. drop acutecomb on in the sequences `iotadieresis.sc acutecomb` and `upsilondieresis.sc acutecomb` as they may occur if iotadieresistonos or upsilondieresistonos are uppercased mechanically.
2. drop tonos on uppercase letters followed or preceded by uppercase letters.
3. add dieresis to Iota and Upsilon when after a vowel, meaning when in a diphthong.
4. drop tonos on uppercase letters followed or preceded by a space and uppercase letters, except for standalone Etatonos (including when at the start or end of a line).

[GoogleSans-Regular.ttf.zip](https://github.com/googlefonts/googlesans/files/5950614/GoogleSans-Regular.ttf.zip)


The same could be applied to the smallcaps but this behaviour is partially implemented in Google Sans with the default smallcaps (they don't have tonos) and etatonos.sc between spaces keeps its tonos.

```
@grk_UPPERCASE_TONOS = [ Alphatonos Epsilontonos Etatonos Iotatonos Omicrontonos Upsilontonos Omegatonos];

@grk_UPPERCASE_NO_TONOS = [ Alpha Epsilon Eta Iota Omicron Upsilon Omega ];

@grk_punctuation_special = [space hyphen endash emdash underscore];

feature calt {
# ===============
# BEGIN GREEK
# ===============
lookup grek_calt_case_marks_dieresistonos {
# Drop acutecomb when iotadieresistonos, upsilondieresistonos have been uppercased mechanically
sub Iotadieresis acutecomb by Iotadieresis;
sub Upsilondieresis acutecomb by Upsilondieresis;
} grek_calt_case_marks_dieresistonos;

lookup grek_calt_case_marks_diphthong {
# Add dieresis on Iota or Upsilon after an uppercase letter
sub @grk_UPPERCASE_TONOS [Iota Upsilon]' by [Iotadieresis Upsilondieresis];
} grek_calt_case_marks_diphthong;

lookup grek_calt_case_marks_drop_tonos {
# Drop tonos from uppercase letters before and after other uppercase letters
# Add dieresis on Iota or Upsilon after an uppercase letter
sub @grk_UPPERCASE_TONOS' @grk_UPPERCASE by @grk_UPPERCASE_NO_TONOS;
sub @grk_UPPERCASE @grk_UPPERCASE_TONOS' by @grk_UPPERCASE_NO_TONOS;
} grek_calt_case_marks_drop_tonos;

lookup grek_calt_case_marks_drop_tonos_special {
# Drop tonos from uppercase letters when after or before a space in an all-caps sequence,
# except for Etatonos
ignore sub @grk_punctuation_special Etatonos @grk_punctuation_special;
sub @grk_UPPERCASE @grk_punctuation_special @grk_UPPERCASE_TONOS' by @grk_UPPERCASE_NO_TONOS;
ignore sub @grk_punctuation_special Etatonos;
sub @grk_punctuation_special @grk_UPPERCASE_TONOS' by @grk_UPPERCASE_NO_TONOS;
ignore sub Etatonos @grk_punctuation_special;
sub @grk_UPPERCASE_TONOS' @grk_punctuation_special by @grk_UPPERCASE_NO_TONOS;
} grek_calt_case_marks_drop_tonos_special;

} calt;
```

**Comment by moyogo** [comment]
@irenevl Does this [Google Sans Regular TTF](https://github.com/googlefonts/googlesans/files/5950614/GoogleSans-Regular.ttf.zip) behave correctly with uppercase for you?

**Comment by irenevlachou** [comment]
> @chrissimpkins this doesn't test anything meaningful.
> The `sub [space hyphen softhyphen endash emdash underscore] etatonos' [space hyphen softhyphen endash emdash underscore comma] by Etatonos;` isn't correct either. The locl feature should definitely not uppercase the etatonos when between spaces because the ή word shouldn't always be uppercase, nor should the case feature because the case feature is for adjusting glyphs in all-caps sequences and not for uppercasing glyphs.
> 
> There should be a feature that drops the tonos marks in all-capital sequences, except on the word ή, and adds dieresis on the iota or upsilon in diphthongs.
> 
> The tonos-dropping is described on Gerry Leonidas’ [_Case conversion for monotonic Greek_](https://leonidas.net/greek-type-design/case-conversion-for-monotonic-greek/) and both tonos-dropping and dieresis-adding are described on MDN’s [_CSS text-transform_ documentation page](https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform#uppercase_greek_vowels).
> 
> Specifically, this means that `"Μήλα ή αχλάδια".upper()"`, in other words `"ΜΉΛΑ Ή ΑΧΛΆΔΙΑ"` looks like `"ΜΗΛΑ Ή ΑΧΛΑΔΙΑ"`. We should have:
> 
> `ΜΉΛΑ Ή ΑΧΛΆΔΙΑ`:
> 
> ```
>  Mu|Eta|Lambda|Alpha|space|Etatonos|space|Alpha|Chi|Lambda|Alpha|uni0394|Iota|Alpha
> ```
> 
> instead of the current
> `ΜΉΛΑ Ή ΑΧΛΆΔΙΑ`:
> 
> ```
> Mu|Etatonos|Lambda|Alpha|space|Etatonos|space|Alpha|Chi|Lambda|Alphatonos|uni0394|Iota|Alpha
> ```

Hi Denis,

that is all correct, the difference is that most of operating systems take care of that issue already, so this isn't something that we should deal in a font level. And because of that we just need an exception of the rule hence the substitution of Etatonos.

**Comment by moyogo** [comment]
> the difference is that most of operating systems take care of that issue already, so this isn't something that we should deal in a font level. And because of that we just need an exception of the rule hence the substitution of Etatonos.

I like the idea of not implementing this behaviour in the fonts. But then why do it for Etatonos?

**Comment by irenevlachou** [comment]
the problem is that etatonos, as a grammatical conjunction (this is when etatonos is a stand-alone word), has a different behaviour than the rest of the UC when we switch everything to all caps. When the rest need to drop the tonos, the conjunction etatonos needs to keep it in order to be obvious that is a conjunction.  This is something that operating systems don't know, so it drops the tonos everywhere even in the case of the conductive etatonos. This is what I was trying to fix by adding the fea, to create an exception.

**Comment by moyogo** [comment]
> When the rest need to drop the tonos, the conjunction etatonos needs to keep it in order to be obvious that is a conjunction. 
> This is something that operating systems don't know, so it drops the tonos everywhere even in the case of the conductive etatonos.

OK. Hopefully most will do it properly soon.

Should we do the same for the dieresis on diphthongs? For example, while using TextEdit in Greek, transforming to uppercase removes the tonos but doesn't add the dieresis in "Νεράιδα", it becomes "ΝΕΡΑΙΔΑ" instead of "ΝΕΡΑΪΔΑ".
Node does the following:
```
> "Νεράιδα".toLocaleUpperCase("el")
ΝΕΡΑΪΔΑ
```

@chrissimpkins 
For Etatonos, we need to check that standalone Eta becomes Etatonos in all-caps sequences, that standalone Eta becomes etatonos.sc.ss06 with the c2sc feature, and that standalone etatonos becomes etatonos.sc.ss06 with the smcp feature. Most of the issues with smallcaps are because of the substitution in the locl feature which shouldn't be there.

Additionaly the substitution should not have softhyphen in the before or after context. The softhyphen is supposed to be used for hyphenation, it splits words at line boundaries.

ΜΗΛΑ Ή ΑΧΛΑΔΙΑ
- current: Mu|Eta|Lambda|Alpha|space|Etatonos|space|Alpha|Chi|Lambda|Alpha|uni0394|Iota|Alpha
- expected: Mu|Eta|Lambda|Alpha|space|Etatonos|space|Alpha|Chi|Lambda|Alpha|uni0394|Iota|Alpha

ΜΗΛΑ Η ΑΧΛΑΔΙΑ
- current: Mu|Eta|Lambda|Alpha|space|**Eta**|space|Alpha|Chi|Lambda|Alpha|uni0394|Iota|Alpha
- expected: Mu|Eta|Lambda|Alpha|space|**Etatonos**|space|Alpha|Chi|Lambda|Alpha|uni0394|Iota|Alpha

ΜΗΛΑ Η
- current: Mu|Eta|Lambda|Alpha|space|**Eta**
- expected: Mu|Eta|Lambda|Alpha|space|**Etatonos**

Η ΑΧΛΑΔΙΑ
- current: **Eta**|space|Alpha|Chi|Lambda|Alpha|uni0394|Iota|Alpha
- expected: **Etatonos**|space|Alpha|Chi|Lambda|Alpha|uni0394|Iota|Alpha

Μήλα ή αχλάδια
- current: Mu|etatonos|lambda|alpha|space|**Etatonos**|space|alpha|chi|lambda|alphatonos|delta|iota|alpha
- expected: Mu|etatonos|lambda|alpha|space|**etatonos**|space|alpha|chi|lambda|alphatonos|delta|iota|alpha

Μήλα ή αχλάδια
- features: smcp
- current: Mu|etatonos.sc|lambda.sc|alpha.sc|space|**Etatonos**|space|alpha.sc|chi.sc|lambda.sc|alphatonos.sc|delta.sc|iota.sc|alpha.sc
- expected: Mu|etatonos.sc|lambda.sc|alpha.sc|space|**etatonos.sc.ss06**|space|alpha.sc|chi.sc|lambda.sc|alphatonos.sc|delta.sc|iota.sc|alpha.sc

Μήλα ή
- features: smcp
- current: Mu|etatonos.sc|lambda.sc|alpha.sc|space|**etatonos.sc**
- expected: Mu|etatonos.sc|lambda.sc|alpha.sc|space|**etatonos.sc.ss06**

ή αχλάδια
- features: smcp
- current: **etatonos.sc**|space|alpha.sc|chi.sc|lambda.sc|alphatonos.sc|delta.sc|iota.sc|alpha.sc
- expected: **etatonos.sc.ss06**|space|alpha.sc|chi.sc|lambda.sc|alphatonos.sc|delta.sc|iota.sc|alpha.sc

ΜΗΛΑ Η ΑΧΛΑΔΙΑ
- features: c2sc
- current: uni03BC.sc|eta.sc|lambda.sc|alpha.sc|space|**eta.sc**|space|alpha.sc|chi.sc|lambda.sc|alpha.sc|delta.sc|iota.sc|alpha.sc
- expected: uni03BC.sc|eta.sc|lambda.sc|alpha.sc|space|**etatonos.sc.ss06**|space|alpha.sc|chi.sc|lambda.sc|alpha.sc|delta.sc|iota.sc|alpha.sc

ΜΗΛΑ Η
- features: c2sc
- current: uni03BC.sc|eta.sc|lambda.sc|alpha.sc|space|**eta.sc**
- expected: uni03BC.sc|eta.sc|lambda.sc|alpha.sc|space|**etatonos.sc.ss06**

Η ΑΧΛΑΔΙΑ
- features: c2sc
- current: **eta.sc**|space|alpha.sc|chi.sc|lambda.sc|alpha.sc|delta.sc|iota.sc|alpha.sc
- expected: **etatonos.sc.ss06**|space|alpha.sc|chi.sc|lambda.sc|alpha.sc|delta.sc|iota.sc|alpha.sc

Μήλα ή Αχλάδια
- features: smcp
- current: Mu|etatonos.sc|lambda.sc|alpha.sc|space|**Etatonos**|space|Alpha|chi.sc|lambda.sc|alphatonos.sc|delta.sc|iota.sc|alpha.sc
- expected: Mu|etatonos.sc|lambda.sc|alpha.sc|space|**etatonos.sc.ss06**|space|Alpha|chi.sc|lambda.sc|alphatonos.sc|delta.sc|iota.sc|alpha.sc

Μήλα ή
- features: smcp
- current: Mu|etatonos.sc|lambda.sc|alpha.sc|space|**Etatonos**
- expected: Mu|etatonos.sc|lambda.sc|alpha.sc|space|**etatonos.sc.ss06**

ή Αχλάδια
- features: smcp
- current: **Etatonos**|space|Alpha|chi.sc|lambda.sc|alphatonos.sc|delta.sc|iota.sc|alpha.sc
- expected: **etatonos.sc.ss06**|space|Alpha|chi.sc|lambda.sc|alphatonos.sc|delta.sc|iota.sc|alpha.sc

**Comment by moyogo** [comment]
> Should we do the same for the dieresis on diphthongs?

Oh, never mind. That's doomed since the tonos for context is dropped by the uppercasing :-/

**Comment by moyogo** [comment]
@irenevl On further thought, I don't think the current approach of changing standalone eta is correct.

A. The current approach only supports broken uppercase.
There are 3 ways applications uppercase Greek:
1. mechanically uppercase with Unicode case mapping, keeping all the tonos and dieresis as they are — TextEdit in English does this, InDesign does this when the language specified is not Greek, all browsers do this with `text-tranform: uppercase` when the language specified is not Greek and some do this even when Greek is specified.
2. uppercase and drop all tonos, without adding dieresis on dipthongs — TextEdit in Greek does this.
3. uppercase, add dieresis in diphthongs, drop the tonos except for standalone etatonos — InDesign does this when language is set to Greek, some browsers do this with `text-tranform: uppercase` when the language specified is Greek. 

This means that the current implementation is only meant to work properly with applications that do 2. a semi-correct Greek vowels uppercase, but calling this semi-correct is generous, it is more broken than not dropping anything since it prevents the font from adding dieresis in diphthongs.

B. The current approach assumes standalone Etatonos is only the grammatical conjunction but it may just be the letter. For example: "πατάς το Η στο πληκτρολόγιο" (press Η on the keyboard).

So, preferably, we shouldn't handle this at the font level at all and let the application or the user uppercase Greek vowels correctly, meaning assume anything that doesn’t do A.3 isn't the font’s fault.

If instead, we consider this is something that should be fixed at the font level, the font should do the right things when it can, meaning handle A.1 properly and not do anything about A.2 since it could be wrong in B and broken with diphthongs anyway.

**Comment by irenevlachou** [comment]
> 1. mechanically uppercase with Unicode case mapping, keeping all the tonos and dieresis as they are — TextEdit in English does this, InDesign does this when the language specified is not Greek, all browsers do this with `text-tranform: uppercase` when the language specified is not Greek and some do this even when Greek is specified.
> 2. uppercase and drop all tonos, without adding dieresis on dipthongs — TextEdit in Greek does this.
> 3. uppercase, add dieresis in diphthongs, drop the tonos except for standalone etatonos — InDesign does this when language is set to Greek, some browsers do this with `text-tranform: uppercase` when the language specified is Greek.
> 
> This means that the current implementation is only meant to work properly with applications that do 2. a semi-correct Greek vowels uppercase, but calling this semi-correct is generous, it is more broken than not dropping anything since it prevents the font from adding dieresis in diphthongs.
> 

Thank you for describing the problem so well.
This all correct and I absolutely agree, we shouldn't touch any of these issues since are half fixes in the best case.

> B. The current approach assumes standalone Etatonos is only the grammatical conjunction but it may just be the letter. For example: "πατάς το Η στο πληκτρολόγιο" (press Η on the keyboard).

Yes that's how it is, the only use of a standalone etatonos `ή` is as a grammatical conjunction and nothing else :)
You can have eta's `η` `Η` without a tonos, as you write, but they would never take an accent.
The reason I'm trying to fix the etatonos is because I think it has a great importance in understanding and correct reading of text and since its use is so specific, I think it's easy to define.

**Comment by chrissimpkins** [comment]
Possible to summarize what is actionable here?

What do we need to do with the current feature in `case` and `locl`?  And do we still want to add the regression tests that Denis indicated in https://github.com/googlefonts/googlesans/issues/157#issuecomment-776006142?

**Comment by moyogo** [comment]
> Possible to summarize what is actionable here?
> 
> What do we need to do with the current feature in `case` and `locl`? And do we still want to add the regression tests that Denis indicated in [#157 (comment)](https://github.com/googlefonts/googlesans/issues/157#issuecomment-776006142)?

Here is what I recommend we do:

1. We should remove the substitution from the locl feature.
  The `sub [space hyphen softhyphen endash emdash underscore] etatonos' [space hyphen softhyphen endash emdash underscore] by Etatonos;` in the locl feature always transforms "α ή β" into "α Ή β".
We don't want lowercase etatonos to become Etatonos in that context.

2. We should remove the substitution from the case feature.
  The `sub [space hyphen softhyphen endash emdash underscore] etatonos' [space hyphen softhyphen endash emdash underscore] by Etatonos;` in the case feature does the same but only when the case feature is applied.
The case feature is meant to adjust the position of glyphs in all-caps context (for example raising the hyphen). The Etatonos would already be uppercase in all-caps text anyway.

3. We should modify the substitution for the smallcaps.
  The `sub [space hyphen softhyphen endash emdash underscore] etatonos.sc' [space hyphen softhyphen endash emdash underscore comma] by etatonos.sc.ss06;` in the calt feature transforms the standalone etatonos.sc (with no visible tonos by default) into the etatonos.sc.ss06 (with visible tonos). However it only does this when preceded and followed by the space or dashes.
  A. `[space hyphen softhyphen endash emdash underscore]` should be `[space hyphen nbspace endash emdash underscore]` with nbspace instead of softhyphen, as softhyphen is used in hyphenation and nbspace is a valid context.
  B. We should add rules so the substitution also occurs at line boundaries in case of line wrapping.
  C. We should add a rule so smallcaps diphthongs with tonos have a dieresis, for example άι should become `alphatonos.sc|iotadieresis.sc` (the tonos is invisible).

**Comment by chrissimpkins** [comment]
Thank you very much Denis.  I really appreciate it.

@irenevl are you in agreement about the recommendations in https://github.com/googlefonts/googlesans/issues/157#issuecomment-777234092?  If so, I think that I can take care of everything from 1 - 3A and get files into your hands.  I'll need additional input on how to support 3B, 3C 

I will also add a set of regression tests on these etatatonos/Etatonos issues so that we can have a look at all of the changes that happen as we make the changes (e.g., as Denis demonstrated in https://github.com/googlefonts/googlesans/issues/157#issuecomment-776006142)

**Comment by irenevlachou** [comment]
sorry for the late reply, I agree with @moyogo proposal.
I'm not sure how to apply 3B and I think 3C is already working with no special fea, at least in ID.
Since the diphthongs don't work at all in apple's apps tranformations, I wouldn't bother to fix just the sc.

https://user-images.githubusercontent.com/11784297/108207529-8e9db080-7130-11eb-963b-3e17512aa3d0.mov

**Comment by chrissimpkins** [comment]
@moyogo @irenevl I implemented my understanding of https://github.com/googlefonts/googlesans/issues/157#issuecomment-777234092 in https://github.com/googlefonts/googlesans/pull/397

Will you please confirm that these changes are as you outlined here?  Static and variable fonts are available for download in https://github.com/googlefonts/googlesans/actions/runs/1279745046.  Ty!

**Comment by chrissimpkins** [comment]
Shaping changes with the fea updates were pushed in https://github.com/googlefonts/googlesans/pull/397/commits/44b84f75f7a7a598d6bcb5f021b91e556b13d384

The following output:

"Mu|etatonos|lambda|alpha|space|**Etatonos**|space|alpha|chi|lambda|alphatonos|delta|iota|alpha"

becomes:

"Mu|etatonos|lambda|alpha|space|**etatonos**|space|alpha|chi|lambda|alphatonos|delta|iota|alpha"

in the text run that we have on the case feature.  We don't currently have a locl regression test but it looks like we should see the same change in locl.  This is what we want?

**Comment by irenevlachou** [comment]
Thanks @chrissimpkins 
The etatonos works fine in case conversion in lc->uc.
In uc->sc the tonos disappears but this is because of etatonos default in small caps. That's ok, too rare case to worry about and it can be accented if the user turns on the ss06–for accented greek sc.
What seems to be broken is th lc->sc conversion, not for just etatonos but for every greek glyph.

**Comment by chrissimpkins** [comment]
Thanks Irene.

> The etatonos works fine in case conversion in lc->uc.
In uc->sc the tonos disappears but this is because of etatonos default in small caps. That's ok, too rare case to worry about and it can be accented if the user turns on the ss06–for accented greek sc.

I am reading the above to mean that the changes in #397 based on Denis's comments are acceptable for the etatonos/Etatonos issue

> What seems to be broken is th lc->sc conversion, not for just etatonos but for every greek glyph.

Hmm. Looks ok to me. Where are you seeing a problem?


![greek-smcp](https://user-images.githubusercontent.com/4249591/135298546-ce2c6cfb-3d06-443b-a442-614159363c6d.gif)

**Comment by irenevlachou** [comment]
actually it's only in Adobe apps, InDesign 16.4 and Illustrator 25.4.1

**Comment by chrissimpkins** [comment]
> actually it's only in Adobe apps, InDesign 16.4 and Illustrator 25.4.1

OK, thanks.  I'll open an issue to look into it.  I'm not sure why this would be the case. Perhaps an Adobe bug for some reason?

**Comment by chrissimpkins** [comment]
> > actually it's only in Adobe apps, InDesign 16.4 and Illustrator 25.4.1
> 
> OK, thanks. I'll open an issue to look into it. I'm not sure why this would be the case. Perhaps an Adobe bug for some reason?

https://github.com/googlefonts/googlesans/issues/403
