### ISSUE TITLE
ss03 colon substitution conflict with calt substitution

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans#178]
`ss03`:

```
sub colon by colon.ss03;
```

is trumped by the `calt`:

```
sub [zero one two three four five six seven eight nine] colon' [zero one two three four five six seven eight nine] by colon.time;
```

so we do not get the expected `colon.ss03` when stylistic set 03 is activated

**Comment by davelab6** [comment]
Related to this, a google designer just reached out to me to ask about the automatic colon substitution. 

![image (66)](https://user-images.githubusercontent.com/261579/129960264-b94443ab-ad1e-4dc7-bd6e-6f237ed20625.png)
![image](https://user-images.githubusercontent.com/261579/129960269-4874c803-45e2-4594-b783-db18f990e412.png)

Perhaps we can add a 'look behind' rule to the substitution so that if there is a `<colon> <1 to X chars> <numbers> <colon> <numbers>` sequence, then then 2nd colon is not substituted. 

I'm not sure what the value of X should be. 

It could also be even more narrow, like `<colon> <space> <numbers> <colon> <numbers>`

**Comment by chrissimpkins** [comment]
The goal is to make sure that colons always have the same vertical alignment when multiple colons are included in a line of text irrespective of context?
