### ISSUE TITLE
Transformed components

### ISSUE THREAD

**Issue by madig** [googlefonts/googlesans#459]
We now fail on the new fontbakery check:

```
 >> Check:   com.google.fonts/check/transformed_components
    Desc:    Ensure component transforms do not perform scaling or rotation.
    Files:   GoogleSansText-MediumItalic.ttf

     FAIL The following glyphs had components with scaling or rotation:

           • uni0547 (component uni0549)
           • uni0577.sc (component uni0579.sc)
           • eternityarmrf (component eternityarmlf)
           • uni0A51 (component uni0A4D)
           • uni1CB9 (component uni1C92)
           • uni1CBE (component uni1CB2)
           • uni10F9 (component uni10D2)
           • uni10FE (component uni10F2)
           • uni1207 (component _geezpart11)
           • uni12AF (component _geezpart11)

          [code: transformed-components]
    Result: FAIL
```

---

Includes components from Armenian, Ethiopic, Georgian, Gurmukhi

**Comment by chrissimpkins** [comment]
It looks like this is the rationale thread.  https://github.com/googlefonts/fontbakery/issues/2011

From what I can tell, this only applies to fonts with TT instructions?

It sounds like [the "fix" can happen at the compiler level](https://github.com/googlefonts/fontbakery/issues/2011#issuecomment-914984693) rather than modifying sources if we decide to address this.  This is a check that has been in place on the G Fonts profile and was apparently just moved to the universal profile that we are based on in the last few weeks / in latest fontbakery release.

Thoughts?  Have you run into problems with this issue?

**Comment by chrissimpkins** [comment]
> From what I can tell, this only applies to fonts with TT instructions?

And only those hinted with ttfa IIUC

**Comment by chrissimpkins** [comment]
Maybe more to it than that as you get into VF format land and there are cross-master differences in the transforms.  See https://github.com/googlefonts/fontmake/issues/595#issuecomment-554420850.

It sounds like this is something that we should address.

**Comment by chrissimpkins** [comment]
Will need to lay eyes on those glyphs to see if this is an actual bug in our current designs or just a theoretical problem that we will avoid going forward.  OK to ignore the check in our fontbakery profile for now so that the active script merges pass CI.

**Comment by chrissimpkins** [comment]
Raph's script to decompose components with mismatched 2x2 matrices.  Glyphs

https://gist.github.com/raphlinus/c31c92af12aab5aa62a975d0cf4c7c2a

**Comment by chrissimpkins** [comment]
https://github.com/googlefonts/googlesans/pull/460

It looks like this is going to fail on all of the open PR's.  We may as well address it now and then rebase the script merge PR's.

**Comment by chrissimpkins** [comment]
There are shaping regressions when we attempt to address this by decomposing transformed components at compile time:

https://github.com/googlefonts/googlesans/pull/460#issuecomment-1054543501
