### ISSUE TITLE
Anchor usage in /t_f 

### ISSUE THREAD

**Issue by Hoolean** [googlefonts/googlesans#526]
## Issue

During the Lao Loopless QA, Hanna observed the following arrangement in our Latin sources:

> 1) Spotted a discrepancy in anchor placement in the 
		regular Display Upright vs Italic
> 2) Does it require all these anchors? Can it get simplified?

> | Upright | Italic |
> | - | - |
> | ![image](https://user-images.githubusercontent.com/2150762/188863238-4a7612ed-2da7-4660-a222-8f9144215535.png) | ![image](https://user-images.githubusercontent.com/2150762/188863301-e0dbf3b3-a970-41af-8219-59882b22b9b8.png) |

## Questions

- [ ] Do we want to change the Latin sources here?
- [ ] Do we want to filter the anchors that we propagate to the Loopless fonts?

@chrissimpkins @MariannaPaszkowska @belluzj I would be interested to hear your thoughts here : )

**Comment by chrissimpkins** [comment]
Likely yes.  If this is not an active bug exposed to end users, let's add this to Q4 work targeting the v11 release.  Adding milestone.  If this is an active user-facing bug issue rather than anchor cleanup, please let me know and we'll prioritize a point release in short order after we roll out v10.000. Ty for raising it!

**Comment by chrissimpkins** [comment]
To address your question about the downstream families, let's address the issue at its source (here) rather than impose a filtered import into families that import the upstream Latin.
