### ISSUE TITLE
Potential shaping issues in Odia

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans#530]
During testing, I observed some shaping inconsistencies between Odia in Noto Sans and Google Sans. Could you please clarify if that's intentional? @kalapi @Hoolean @belluzj 

<img width="1120" alt="Shaping_Odia" src="https://user-images.githubusercontent.com/22956348/190474919-8108d036-b092-4731-afbe-add5568a1dd8.png"> <br/>
_That's a snapshot from Figma_ 
<br/><br/>
Here is where I noticed differences:
`ର୍ଖି`    iMatra-reph ligature
`ଡ଼ୁ` `ଡ଼ୂ`   u & uuMatra alternate 4
`କ୍କ୍ଲ` `ଗ୍ଲ୍ମ` `କ୍ଲ୍କ`  Recompose below-base consonant to halant+fullconsonants
`ତ୍କ` `ତ୍ପ`  Included conjuncts
`ନ୍ଧ୍ଭ`  Included conjuncts
`ର୍ଥି` `ର୍ଧି`  iMatra-Reph ligatures

CC @chrissimpkins

**Comment by Hoolean** [comment]
Hello Marianna! Thank you for raising these : )

Jonny – who did the original QA – took a look this morning:

> `ର୍ଖି iMatra-reph ligature` `ର୍ଥି ର୍ଧି iMatra-Reph ligatures`
In both of these instances GS Oriya appears correct as it's making the iMatra-Reph substitution where Noto isn't.

> `ଡ଼ ଡ଼ୂ u & uuMatra alternate 4`
GS Oriya is likely correct, over Noto, as the nukta is actually being dropped in favour of the umatra/uumatra glyphs. This, I think, is to do with similar nasalisation sounds from both marks, so nukta not being necessary.

> `କ୍କ୍ଲ ଗ୍ଲ୍ମ କ୍ଲ୍କ Recompose below-base consonant to halant+fullconsonants`
These are conjunct clusters not supported in the GoogleSans encoding

> `ତ୍କ ତ୍ପ Included conjuncts`
This looks like a stylistic difference, to me. Worth checking, I guess.

> `ନ୍ଧ୍ଭ Included conjuncts`
GoogleSans /n_dh_bha-oriya uses /ba-oriya.blwf instead of /bha-oriya.blwf in its decomposed conjunct. This appears to be wrong when compared to Noto.

> In short, I think the final one could be a real error - the rest, not so much.

@kalapi @chrissimpkins @MariannaPaszkowska How should we proceed?

**Comment by kalapi** [comment]
Hi @MariannaPaszkowska @Hoolean,

Thanks for this, I've had no time to respond to this while I prepare the Gujarati package, but Johnny's observations are largely correct. with the exception of:

1.
> `କ୍କ୍ଲ ଗ୍ଲ୍ମ କ୍ଲ୍କ Recompose below-base consonant to halant+fullconsonants`
> These are conjunct clusters not supported in the GoogleSans encoding

With regards to the 2nd tier/level _vattus_ (below-base marks), we made a conscious decision to limit shaping and recompose the 3rd (or any more consonants) as a full consonant with an explicit halant. This is mainly because it's very rare to have three-tier combinations in Odia (other than the ones already included), and where necessary (like transliteration of loan-words) modern readers prefer having an explicit halant instead of endlessly stacking _vattus_.

2.
> `ତ୍କ ତ୍ପ Included conjuncts`
> This looks like a stylistic difference, to me. Worth checking, I guess.

Yes, this is indeed a stylistic choice.

3.
> `ନ୍ଧ୍ଭ Included conjuncts`
> GoogleSans /n_dh_bha-oriya uses /ba-oriya.blwf instead of /bha-oriya.blwf in its decomposed conjunct. This appears to be wrong when compared to Noto.

I'm still looking into this. The vattu is definitely incorrect, but i'm wondering whether it's the shape or the input sequence which needs correction. I.e. the glyph is probably `n_dh_ba-oriya` and not `n_dh_bha-oriya`. I've emailed our language consultant and waiting for a reply, in the meantime one of our designers is checking the glyph list research.

I should have a response for point 3 by mid-end of next week.

**Comment by kalapi** [comment]
4.
> `ଡ଼ ଡ଼ୂ u & uuMatra alternate 4`
> GS Oriya is likely correct, over Noto, as the nukta is actually being dropped in favour of the umatra/uumatra glyphs. This, I think, is to do with similar nasalisation sounds from both marks, so nukta not being necessary.

Sorry, missed to remark on this, very strange, these consonants need to use the `.alt04` of the uMatra and uuMatra. I think this is happening because of the missing context of the nukta in the sub rule. This should be an easy fix. I'll try this early next week.

**Comment by kalapi** [comment]
Hello @MariannaPaszkowska, @chrissimpkins, and @Hoolean 

I've included fixes to issues 3 & 4 described in my messages above.

<img width="419" alt="Screenshot 2022-09-21 at 9 07 24 PM" src="https://user-images.githubusercontent.com/15804460/191636384-5a73af7c-6815-4d09-beb5-0d3ef52b04ce.png">

[2022-09-21_GoogleSansOdia_V1.000_BETA04.zip](https://github.com/googlefonts/googlesans/files/9621296/2022-09-21_GoogleSansOdia_V1.000_BETA04.zip)

**Comment by Hoolean** [comment]
Hi @kalapi! Thank you for the new sources: I noticed changes that I wanted to check before completing the merge.

In the uprights, about 8 glyphs are different, but in the italics, there are about 100. These are largely spacing changes, but there are also changes to anchor positions and curves too. Are the italic changes intentional, or might the sources be based on an older version?

I noticed that the latest build is labelled "BETA04" as opposed to "BETA06", and that there was a small regression in the feature file (see below), so thought this would be worth checking : )

![image](https://user-images.githubusercontent.com/2150762/191951154-9944ffff-b921-4a0c-a5f0-a1f769d7e0ea.png)

**Comment by kalapi** [comment]
Hi @Hoolean I'm looking into this now, i'll have an update for you in an hour.

**Comment by kalapi** [comment]
Hi @Hoolean,

Thanks so much for checking for regressions! I used an older package as a source for fixes (still don't know why?!) Apologies for the inconvenience. 

I'm attaching a new package with the fixes. Please not that you will still see a significant diff in the italics. This is because I reworked a glyph that is the metrics source for almost all of the others.

Please let me know if you find any other issue.

[2022-09-26_GoogleSansOdia_V1.000_BETA06.zip](https://github.com/googlefonts/googlesans/files/9647846/2022-09-26_GoogleSansOdia_V1.000_BETA06.zip)

**Comment by Hoolean** [comment]
Hello all!

Thank you for the latest sources @kalapi :tada:

@MariannaPaszkowska @chrissimpkins Jonny found that the fixes work correctly in Kalapi's TTFs, and Jany and I similarly saw no obvious visual regressions in the merged sources. For this reason, we have confidence in the changes, and believe we can proceed to preparing the branch for review.

---

@kalapi, in the end, these were the changes we saw in the merged Italic:

| Pre-fix | Post-fix |
|-|-|
| ![image](https://user-images.githubusercontent.com/2150762/193035782-96e89d0d-aa54-4c96-bf61-f75cf4773bc9.png) | ![image](https://user-images.githubusercontent.com/2150762/193035831-9441833a-3deb-48a4-9f5c-92857672c322.png) |
