### ISSUE TITLE
Excessive number of lookups / duplicates

### ISSUE THREAD

**Issue by behdad** [googlefonts/googlesans#567]
GS seems to have over 1600 GSUB lookups. That seems way too many. I'm sure this can be optimized down.

Moreover, many of them look *identical*.  For example:
```
      <Lookup index="24"> 
        <LookupType value="1"/> 
        <LookupFlag value="0"/> 
        <!-- SubTableCount=1 --> 
        <SingleSubst index="0"> 
          <Substitution in="colon" out="colon.loclGEO"/> 
          <Substitution in="semicolon" out="semicolon.loclGEO"/> 
        </SingleSubst> 
      </Lookup> 
      <Lookup index="25"> 
        <LookupType value="1"/> 
        <LookupFlag value="0"/> 
        <!-- SubTableCount=1 --> 
        <SingleSubst index="0"> 
          <Substitution in="colon" out="colon.loclGEO"/> 
          <Substitution in="semicolon" out="semicolon.loclGEO"/> 
        </SingleSubst> 
      </Lookup> 
```
or, much worse, lookups 86 to 136 are all the same:
```
     <Lookup index="86"> 
        <LookupType value="1"/> 
        <LookupFlag value="512"/><!-- markAttachmentType[2] --> 
        <!-- SubTableCount=1 --> 
        <SingleSubst index="0"> 
          <Substitution in="uni093F" out="uni093F.alt4"/> 
        </SingleSubst> 
      </Lookup> 
```
Lookups 137 to 260 are all the same!
```
     <Lookup index="260"> 
        <LookupType value="1"/> 
        <LookupFlag value="512"/><!-- markAttachmentType[2] --> 
        <!-- SubTableCount=1 --> 
        <SingleSubst index="0"> 
          <Substitution in="uni093F" out="uni093F.alt5"/> 
        </SingleSubst> 
      </Lookup> 
```
Lookups 261 to 406 are all the same!
```
      <Lookup index="406"> 
        <LookupType value="1"/> 
        <LookupFlag value="512"/><!-- markAttachmentType[2] --> 
        <!-- SubTableCount=1 --> 
        <SingleSubst index="0"> 
          <Substitution in="uni093F" out="uni093F.alt6"/> 
        </SingleSubst> 
      </Lookup> 
```
Lookups 407 to 479 are all the same!
```
      <Lookup index="479"> 
        <LookupType value="1"/> 
        <LookupFlag value="512"/><!-- markAttachmentType[2] --> 
        <!-- SubTableCount=1 --> 
        <SingleSubst index="0"> 
          <Substitution in="uni093F" out="uni093F.alt7"/> 
        </SingleSubst> 
      </Lookup> 
```

Furthermore, there's a lookup (85) in GSUB that has 394 subtables. It's a ChainContextSubstFormat1 subtables. This probably should be regenerated as a Format2 with classes or Format3 with coverages.

We noticed this because of excessive memory use of this font with HarfBuzz.

**Comment by behdad** [comment]
HarfBuzz allocates 64 bytes per lookup and 56 bytes per lookup subtable (including malloc overhead). For this font that adds up to over 250kb currently.

**Comment by davelab6** [comment]
GS is now the result of a dozen merges, so duplication like this isn't totally wild

**Comment by simoncozens** [comment]
This is all Devanagari, and all related to the iMatra width selection. There are two problems here; one is a feaLib issue, one is a fea authoring issue. 

First, the authoring issue. The big lookup with the huge number of subtables, 85, is `dev2_dflt_mar_nep_pres_imatra_contexts_half_forms`. This chooses the correct width of the iMatra glyph to stretch over the sequence following it (in this case, half-form sequences composed of base+virama+base):
![shape](https://user-images.githubusercontent.com/106728/215095345-5d5257a9-c3ba-4d71-bb23-e0f55b4ce2fe.png)

> Sidenote: This is `opsz18-wght734-GRAD0` because it was the first one I could get to compile, and it looks like those substitutions are actually *wrong*; the iMatra should "point" at the stem of the main consonant, like this: ![shape](https://user-images.githubusercontent.com/106728/215095817-c8add829-4b5f-4bcb-b852-8113202af1af.png)

Obviously when you're testing every possible half-form sequence, there are lots of different rules required, and unless you're very careful, you end up with a massive set of subtables. This is because, to implement a contextual rule as the more compact format 2, each glyph class must be expressible as a ClassDef, which requires them to be non-intersecting sets. So for example, just looking at a portion of the lookup:

```fea
        sub iMatra-deva' y-deva.alt3 [ca-deva ha-deva] by iMatra-deva.alt5;
        sub iMatra-deva' s-deva.alt2 ddda-deva by iMatra-deva.alt5;
        sub iMatra-deva' b-deva.alt2 [nga-deva ca-deva dda-deva dddha-deva ddda-deva bba-deva] by iMatra-deva.alt5;
```

`ca-deva` is in two different glyph classes here (and so is `ddda-deva`), so this will not be expressible as a Format 2 subtable. I would either rewrite it using non-intersecting sets like so:

```fea
        sub iMatra-deva' y-deva.alt3 ca-deva by iMatra-deva.alt5;
        sub iMatra-deva' y-deva.alt3 ha-deva by iMatra-deva.alt5;
        sub iMatra-deva' s-deva.alt2 ddda-deva by iMatra-deva.alt5;
        sub iMatra-deva' b-deva.alt2 [nga-deva dda-deva dddha-deva bba-deva] by iMatra-deva.alt5;
        sub iMatra-deva' b-deva.alt2 ca-deva by iMatra-deva.alt5;
        sub iMatra-deva' b-deva.alt2 ddda-deva by iMatra-deva.alt5;
```

(although that's a pain to do by hand - of course I would not do it by hand...), or split the lookup into multiple levels, i.e. dispatch on the first glyph:

```fea
        ...
        sub iMatra-deva' lookup IMatraSelectionY3 y-deva.alt3;
        sub iMatra-deva' lookup IMatraSelectionS2 s-deva.alt2;
        sub iMatra-deva' lookup IMatraSelectionB2 b-deva.alt2;
        ...
```

to subsidiary lookups like so:

```fea
lookup ImatraSelectionY3 {
        sub iMatra-deva' y-deva.alt3 [ca-deva ha-deva] @dev2_dflt_pres_mark_attachment_class_top_marks by iMatra-deva.alt4;
        sub iMatra-deva' y-deva.alt3 [ca-deva ha-deva] by iMatra-deva.alt5;
        sub iMatra-deva' y-deva.alt3 cha-deva @dev2_dflt_pres_mark_attachment_class_top_marks by iMatra-deva.alt5;
        sub iMatra-deva' y-deva.alt3 cha-deva by iMatra-deva.alt6;
} IMatraSelectionY3;
```

The main dispatch lookup would be very small and each of these sublookups would be expressible as format 2.

Now for the tooling bug. The lookups which are all the same are being produced by "inline" contextual substitutions like so:

```fea
        sub iMatra-deva' y-deva.alt3 [ca-deva ha-deva] by iMatra-deva.alt5;
        sub iMatra-deva' s-deva.alt2 ddda-deva by iMatra-deva.alt5;
        sub iMatra-deva' b-deva.alt2 [nga-deva ca-deva dda-deva dddha-deva ddda-deva bba-deva] by iMatra-deva.alt5;
```

This is what the compiler should do under the hood:

```fea
lookup to_alt5 {  sub iMatra-deva by iMatra-deva.alt5; } to_alt5;

        sub iMatra-deva' lookup to_alt5 y-deva.alt3 [ca-deva ha-deva];
        sub iMatra-deva' lookup to_alt5  s-deva.alt2 ddda-deva;
        sub iMatra-deva' lookup to_alt5  b-deva.alt2 [nga-deva ca-deva dda-deva dddha-deva ddda-deva bba-deva];
```

This is what the compiler appears to be actually doing:

```fea
lookup anonymous_lookup_1 { sub iMatra-deva by iMatra-deva.alt5; } anonymous_lookup_1;
lookup anonymous_lookup_2 { sub iMatra-deva by iMatra-deva.alt5; } anonymous_lookup_2;
lookup anonymous_lookup_2 { sub iMatra-deva by iMatra-deva.alt5; } anonymous_lookup_3;

        sub iMatra-deva' lookup anonymous_lookup_1 y-deva.alt3 [ca-deva ha-deva];
        sub iMatra-deva' lookup anonymous_lookup_2 s-deva.alt2 ddda-deva;
        sub iMatra-deva' lookup anonymous_lookup_3 b-deva.alt2 [nga-deva ca-deva dda-deva dddha-deva ddda-deva bba-deva];
```

I said on the chat that the compiler should merge common *subtables* in the binary, but I wonder if that does not apply to common *lookups*. And indeed it doesn't; see fontTools bugs https://github.com/fonttools/fonttools/issues/512 and https://github.com/fonttools/fonttools/issues/514.

There is a compiler optimization to be made here, and a good one too. It's just not particularly easy given the way fealib currently works.

The workaround is to write the rules explicitly in the `lookup to_alt5` form I wrote under "what the compiler should do" above. Inline substitutions are evil and should be avoided, although they are such a tempting syntax for designers.

**Comment by khaledhosny** [comment]
https://github.com/fonttools/fonttools/issues/2150

**Comment by kalapi** [comment]
Hi @behdad & @simoncozens 

Thanks for the detailed info about this issue. This feature code is my handy work and I tried to optimise the contexts as much as I could but i'm glad to see it can be further optimised. 

I'm happy and eager to discuss possible ways to automate this code output. The included code is generated by a (very crude) Python script I wrote to calculate all the permutations. 

GS Devanagari is one of the first typefaces to implement a contextual half-form conjunct building approach. The usual approach to developing Devanagari fonts is to include a limited set of pre-configured conjuncts which reduces the orthographic coverage/range for emerging contexts of use of the script (such as loan-word transliteration). 

A consequence of building conjuncts on-the-fly is that all other matra combinations end up with longer contexts needing to be defined.

**Comment by simoncozens** [comment]
> The included code is generated by a (very crude) Python script I wrote to calculate all the permutations.

I'd strongly recommend looking at [fez](https://fez.readthedocs.io). It will help you generate feature code, and if you turn on the optimiser, it will also automatically split the rules into Format 2-compatible non-overlapping sets.

**Comment by behdad** [comment]
> [fonttools/fonttools#2150](https://github.com/fonttools/fonttools/issues/2150)

With this fixed the GSUB number if lookups is down from >1600 to 946. Not bad for a small change. Still, need to investigate if those many lookups are needed or can be consolidated.

**Comment by behdad** [comment]
> HarfBuzz allocates 64 bytes per lookup and 56 bytes per lookup subtable (including malloc overhead). For this font that adds up to over 250kb currently.

I've optimized HarfBuzz to lazily load per-lookup accelerators on-demand, so this is less pressing now.
