### ISSUE TITLE
Review diffs dash

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans#582]
Updated diffs can be found here: https://github.com/googlefonts/googlesans/actions/runs/5266444103

Diffs are much cleaner now that I'm not adding multilingual strings to a single harfbuzz buffer.

Only visual difference I can spot is for the string "(650) 555-1234". Kerning for "-1" has changed. "-3" and "-8" are also reported but I don't see a visual shift.

<img width="349" alt="Screenshot 2023-06-14 at 12 47 54" src="https://github.com/googlefonts/googlesans/assets/7525512/130d15a4-7cc2-4826-a508-714d173b11bb">

_Originally posted by @m4rc1e in https://github.com/googlefonts/googlesans/issues/516#issuecomment-1591042286_

**Comment by madig** [comment]
Looking at the diffenator output, I can confirm the hyphen seems to do... something. In strings where there is an explicit script to be determined (e.g. Latin), all is ok, but the number string you see has only "common" characters. What I don't quite understand is that I can't replicate this in an HTML tester in Chrome and Firefox...

**Comment by madig** [comment]
In the string above, only "-12" has kerning in the Display Regular according to the sources (-30 between hyphen and one, +10 between one and two). This is reflected in the new font with updated dependencies, but not the old one (no -30)... unless you set a script like Latin. Since the string only has "common" characters, it only gets the kerning in `kern_dflt`, which does not contain a pair for hyphen and one. Setting e.g. Latin will make it additionally apply kerning between hyphen and one. So, the old font was subtly broken in the edge case where no explicit script of a string could be determined.

The way the new font (updated deps) works, both kerns are applied with and without a proper detected script, so it's more correct.

**Comment by Hoolean** [comment]
Hello all!

We were able to reproduce the behaviour difference in very specific scenarios, with the page and diffenator fonts [here](https://github.com/googlefonts/googlesans/files/11869324/Reproducer.zip):

1. **In HarfBuzz**:
   1. ✔️ Reproduces in Crowbar when shaping without providing a script
   2. :x: Otherwise could not reproduce when a script was provided
2. **In Chrome**:
   1. ✔️ Reproduces **only** when placing the string adjacent to an absolute-positioned span with Latin text (!), which replicates the environment in which diffenator2 displays the string
   2. ❌ Could not immediately reproduce in less-specific contexts (e.g. no span, no absolute positioning)
3. **In Firefox:**
   1. :x: Could not immediately reproduce in the same scenarios as Chrome

We suspect this is related to text segmentation. The old KernFeatureWriter only kerns /hyphen against /one in non-DFLT lookups, whereas the new KernFeatureWriter kerns /hyphen against /one in every circumstance. We think the old behaviour was likely unintentional and the new behaviour is more correct, although we have a little more thinking to do on RTL scripts.

---

@m4rc1e Which environment or library does diffenator2 shape the strings in? Is it similar to the conditions under which we can reproduce in HarfBuzz and Chrome? It is wacky that we managed to hit such a strange HTML/CSS corner case in Chrome's behaviour with diffenator2's output HTML 😁

@MariannaPaszkowska @chrissimpkins Our next steps are to determine whether we can encounter this behavioural difference in production, especially Android. Narrowing down why Chrome behaves the way it does in such a specific scenario would help to progress this; would we be able to collaborate with the browser team here?

**Comment by Hoolean** [comment]
To summarise: the behaviour difference only happens when kerning falls back to the DFLT lookup, and so we need to work out whether this happens naturally or often in the environments we care about, or only through raw HarfBuzz buffers and browsers misbehaving.

**Comment by Hoolean** [comment]
Another potentially uncommon reproduction case: "ཡོངས་ཁྱ(650) 555-1234བ་གསལ" triggers the behavioural difference in Chrome, as the presence of Tibetan coerces the middle string into using the DFLT lookup too. This depends on the presence of a script that has no langsys (and so likely no outlines or encoding) in Google Sans.
