### ISSUE TITLE
Add tabular punctuation 

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans#634]
"It looks like we also have tabular punctuation in GSF that does not exist in GS."

https://github.com/googlefonts/googlesans-flex/issues/937#issuecomment-2083192291

**Comment by belluzj** [comment]
@MariannaPaszkowska what is the glyphset you have in mind in this issue? I looked at GS and it seems to have already almost all the tabular punctuation that GS Flex has (only missing zeroslash.tf and percentbar.tf)

The difference between the two is that in GS Flex, the tabular punctuation is indeed on the same tabular width as the numbers, while in GS, the tabular punctuation is merely multiplexed, i.e. its advance width doesn't vary along the weight axis.

![image](https://github.com/googlefonts/googlesans/assets/3616772/746e44ca-d026-4973-ae05-587b34ed9e0d)

Google Sans (weight axis animation):
![gs_tnum_weight_axis](https://github.com/googlefonts/googlesans/assets/3616772/2578cbfa-c060-4928-ad54-b966bc6795df)


In Google Sans Flex | In Google Sans
-- | --
zero.tf | zero.tf
one.tf | one.tf
two.tf | two.tf
three.tf | three.tf
four.tf | four.tf
five.tf | five.tf
six.tf | six.tf
seven.tf | seven.tf
eight.tf | eight.tf
nine.tf | nine.tf
period.tf | period.tf
comma.tf | comma.tf
colon.tf | colon.tf
semicolon.tf | semicolon.tf
numbersign.tf | numbersign.tf
space.tf | space.tf
cent.tf | cent.tf
currency.tf | currency.tf
dollar.tf | dollar.tf
Euro.tf | Euro.tf
sterling.tf | sterling.tf
plus.tf | plus.tf
minus.tf | minus.tf
multiply.tf | multiply.tf
divide.tf | divide.tf
equal.tf | equal.tf
notequal.tf | notequal.tf
greater.tf | greater.tf
less.tf | less.tf
greaterequal.tf | greaterequal.tf
lessequal.tf | lessequal.tf
plusminus.tf | plusminus.tf
approxequal.tf | approxequal.tf
logicalnot.tf | logicalnot.tf
percent.tf | percent.tf
section.tf | section.tf
zeroslash.tf | 
percentbar.tf | 
yen.tf | yen.tf

**Comment by belluzj** [comment]
If we're adding a zeroslash feature, we need to also add zeroslash.tf

For percentbar.tf, let's check if it's encoded/reachable by features (tnum feature). If it's a usable glyph, let's add to GS, otherwise not.

About which approach is most useful to have in the fonts, it would be good to ask designers from Dalton Maag. Marianna will ask David Berlow and Octavio's opinion.

**Comment by belluzj** [comment]
In Google Sans Flex, the tabular numbers don't seem multiplexed. That is, their advance width changes on the optical size, width, and weight axes. See this gif which shows the size of the highlighted text (tnum feature on) changes along with opsz, width, weight:

![GSF_tnum_not_multiplexed](https://github.com/googlefonts/googlesans/assets/3616772/ac1f3ef2-d1f4-480c-a7d6-6f0dcfda025c)

**Comment by belluzj** [comment]
@MariannaPaszkowska In terms of comparing the two approaches, here is the feedback from our designers:

The approach in Google Sans is our standard approach, and therefore what we'd recommend. It enables mixing weights in tabular data such as financials, while preserving vertical alignment. Google Sans Flex would not allow that because of the lack of multiplexing.

`$1,000,000`
**`$2,000,000`**

The Google Sans Flex approach allows, within a single weight, to mix numbers with punctuation in different places, but that doesn't sound like a common/practical use-case:
```
12345,678
 45678901
   8234,5
```

The only issue we can foresee if you try to apply multiplexing to Google Sans Flex along the weight axis, is that the extreme range of weights might make this impractical, compared to Google Sans. One possible solution is to limit multiplexing to a range of the weight axis, for example from Light (300) to Bold (700), to allow mixing these weights in a table, but letting the Hairline have a smaller advance width, and the Black have a larger width, assuming they're not suitable for tabular data.

Overall our designers advise that you first define what you want the behaviour to be, based on target use-cases for the tabular numbers, then work towards that rather than react to the solutions you have. You may find both approaches don't meet what you actually would want the fonts to work like.

**Comment by MariannaPaszkowska** [comment]
related to the character set #625 - we should add  zeroslash.tf

**Comment by MariannaPaszkowska** [comment]
Decision: we will use punctuation on half widths; thank you, everyone!
